

IPPROTO_UDP = 1
IPPROTO_TCP = 2
IPPROTO_TLS = 3

IPPROTO_NAMES = {
    IPPROTO_UDP: "UDP",
    IPPROTO_TCP: "TCP",
    IPPROTO_TLS: "TLS",
}

FAMILY_IP4 = 0x01
FAMILY_IP6 = 0x02

FAMILY_NAMES = {
        FAMILY_IP4: "IPv4",
        FAMILY_IP6: "IPv6"
}

MAGIC_COOKIE = 0x2112A442
STUN_HEADER_SIZE = 20

CLASS_REQUEST = 0
CLASS_INDICATION = 1
CLASS_SUCCESS = 2
CLASS_ERROR = 3

CLASS_NAMES = {
    CLASS_REQUEST: "Request",
    CLASS_INDICATION: "Indication",
    CLASS_SUCCESS: "Success Response",
    CLASS_ERROR: "Error Response",
}

METHOD_BINDING = 1
METHOD_SHARED_SECRET = 2
METHOD_ALLOCATE = 3
METHOD_REFRESH = 4

METHOD_NAMES = {
    METHOD_BINDING: "Binding",
    METHOD_SHARED_SECRET: "SharedSecret",
    METHOD_ALLOCATE: "Allocate",
    METHOD_REFRESH: "Refresh",
}

ATTR_MAPPED_ADDRESS = 1
ATTR_SOURCE_ADDRESS = 4 # deprecated
ATTR_CHANGED_ADDRESS = 5 # deprecated
ATTR_USERNAME = 6
ATTR_MESSAGE_INTEGRITY = 8
ATTR_ERROR_CODE = 9
ATTR_UNKNOWN_ATTRIBUTE = 0x00a
ATTR_REALM = 0x0014
ATTR_NONCE = 0x0015
ATTR_REQUESTED_ADDRESS_FAMILY = 0x0017
ATTR_XOR_MAPPED_ADDRESS = 0x0020
ATTR_XOR_MAPPED_ADDRESS_OPTIONAL = 0x8020 # optional for the client to use
ATTR_SOFTWARE = 0x8022
ATTR_RESPONSE_ORIGIN = 0x802b
ATTR_OTHER_ADDRESS = 0x802c
ATTR_ALTERNATE_SERVER = 0x8023
ATTR_FINGERPRINT = 0x8028

ATTR_NAMES = {
    ATTR_MAPPED_ADDRESS: "MAPPED-ADDRESS",
    ATTR_USERNAME: "USERNAME",
    ATTR_MESSAGE_INTEGRITY: "MESSAGE-INTEGRITY",
    ATTR_ERROR_CODE: "ERROR-CODE",
    ATTR_UNKNOWN_ATTRIBUTE: "UNKNOWN-ATTRIBUTES",
    ATTR_REALM: "REALM",
    ATTR_NONCE: "NONCE",
    ATTR_REQUESTED_ADDRESS_FAMILY: "REQUESTED-ADDRESS-FAMILY",
    ATTR_XOR_MAPPED_ADDRESS: "XOR-MAPPED-ADDRESS",
    ATTR_XOR_MAPPED_ADDRESS_OPTIONAL: "XOR-MAPPED-ADDRESS",
    ATTR_SOFTWARE: "SOFTWARE",
    ATTR_ALTERNATE_SERVER: "ALTERNATE-SERVER",
    ATTR_FINGERPRINT: "FINGERPRINT",
    ATTR_RESPONSE_ORIGIN: "RESPONSE-ORIGIN",
    ATTR_OTHER_ADDRESS: "OTHER-ADDRESS",
    ATTR_SOURCE_ADDRESS: "SOURCE-ADDRESS",
    ATTR_CHANGED_ADDRESS: "CHANGED-ADDRESS"
}
